//! Type re-export pass ("type linker"), run at the end of every Roblox
//! install.
//!
//! Luau does not propagate `export type` declarations through a module that is just `return require(...)`
//! The solution here is to re-export the types in all link/pointer modules.
//! 
//! DELIBERATE DESIGN DECISION:
//! On the ingest of mirrored packages, we dont export types in our link files because this would require significant backfilling if something changes.
//! Implementing the export logic CLI side gives us flexibility to iterate our solution over time. 
//!
//! ```lua
//! --Pointer file generated by Forest Package Manager.
//! local MODULE = require(script.Parent['X'])
//! export type Foo<T = any?> = MODULE.Foo<T>
//! return MODULE
//! ```
//!
//! Every link in a chain gets the FINAL module's export list, so types flow
//! hop by hop no matter which link is visited first. Rewrites are
//! deterministic and idempotent; a link whose target exports nothing is
//! normalized to the plain `return require(...)` form. A file the pass
//! cannot understand is left exactly as generated and that link's types stay
//! broken, the install itself never fails.

use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use crate::roblox::plan::POINTER_HEADER;

/// First-line prefix of every mirror-generated link kind
const MIRROR_HEADER_PREFIX: &str = "--Generated by the forest ";

/// Local the rewritten link binds its target to. Luau only re-exports types
/// through a local assigned directly from a require() call.
const LOCAL_NAME: &str = "MODULE";

/// This is not a max depth check, but instead how many individual module hops (links) we allow before considering it a cycle.
/// (If you've got more than 32 genuine module hops please reach out)
const MAX_CHAIN: usize = 32;

/// Walk the mount and patch every generated link file with explicit type
/// re-exports. Infallible by design: problems are per-file warnings.
pub fn relink_types(mount: &Path) {
    let mut cache: HashMap<PathBuf, Option<Vec<ExportedType>>> = HashMap::new();
    walk(mount, &mut cache);
}

fn walk(dir: &Path, cache: &mut HashMap<PathBuf, Option<Vec<ExportedType>>>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        // Same exemption as install cleanup: `_`/`.` entries (probably) aren't ours.
        if name.starts_with('_') || name.starts_with('.') { //NOTE: Does anyone start their lua modules files with _? If you do and you see this open an issue.
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            walk(&path, cache);
        } else if name.ends_with(".lua") || name.ends_with(".luau") { //NOTE: Should we start force converting files to .luau?
            relink_file(&path, cache);
        }
    }
}

fn relink_file(path: &Path, cache: &mut HashMap<PathBuf, Option<Vec<ExportedType>>>) {
    let Ok(source) = fs::read_to_string(path) else { return };
    if !is_link(&source) { // Doesnt have the pointer header, skip
        return;
    }
    let Some(expr) = require_expr(&source) else { return }; // No require() found, skip

    let exports = match resolve_exports(path, &expr, cache) {
        Some(exports) => exports,
        None => {
            crate::message::warn(&format!(
                "Could not resolve types through {}; its target's exported types won't be visible.",
                path.display()
            ));
            return;
        }
    };

    let header = source.lines().next().unwrap_or_default(); // Reuse the header of the original source
    let rendered = render(header, &expr, &exports);
    if rendered != source { // No point in writing if the source is the same (less rojo freakouts)
        if let Err(e) = fs::write(path, &rendered) {
            crate::message::warn(&format!("Failed to update {}: {}", path.display(), e));
        }
    }
}

/// Is this source a forest-generated link module?
fn is_link(source: &str) -> bool {
    let first = source.lines().next().unwrap_or_default();
    first == POINTER_HEADER || first.starts_with(MIRROR_HEADER_PREFIX)
}

/// Resolve a link's target through any further links and return the final
/// real module's exported types. `None` = could not resolve; `Some(vec![])`
/// = resolved fine, target exports nothing.
fn resolve_exports(
    link_path: &Path,
    expr: &str,
    cache: &mut HashMap<PathBuf, Option<Vec<ExportedType>>>,
) -> Option<Vec<ExportedType>> {
    let (module_path, module_source) = resolve_final_module(link_path, expr)?;
    if let Some(cached) = cache.get(&module_path) {
        return cached.clone(); // Return cached exports if available
    }
    let exports = Some(extract_exports(&strip_comments(&module_source))); // Found the module, go get exports.
    cache.insert(module_path, exports.clone());
    exports
}

/// Follow the require chain from a link file to the first non-link module,
/// returning its path and source.
fn resolve_final_module(link_path: &Path, expr: &str) -> Option<(PathBuf, String)> {
    let mut current_file = link_path.to_path_buf();
    let mut current_expr = expr.to_string();
    for _ in 0..MAX_CHAIN {
        let target = resolve_one(&current_file, &current_expr)?;
        let source = fs::read_to_string(&target).ok()?;
        if !is_link(&source) {
            return Some((target, source));
        }
        current_expr = require_expr(&source)?; // ? = loud early return None
        current_file = target;
    }
    None
}

/// Extract the argument of the first `require(...)` in the source. Works on
/// both generated forms (`return require(...)` and the rewritten
/// `local MODULE = require(...)`).
fn require_expr(source: &str) -> Option<String> {
    let start = source.find("require(")? + "require(".len();
    let rest = &source[start..];
    let mut depth = 1usize;
    for (i, c) in rest.char_indices() {
        match c {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return Some(rest[..i].trim().to_string());
                }
            }
            _ => {}
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Require-chain resolution: `script…` expression -> filesystem module
// ---------------------------------------------------------------------------

enum Step {
    Parent,
    Child(String),
}

/// Parse a generated `script…` expression into instance steps. Only shapes
/// our generators emit: `.Parent`, `.Ident`, `["name"]`, `['name']`.
fn parse_steps(expr: &str) -> Option<Vec<Step>> {
    let rest = expr.strip_prefix("script")?;
    let chars: Vec<char> = rest.chars().collect();
    let mut steps = Vec::new();
    let mut i = 0;
    while i < chars.len() {
        match chars[i] {
            '.' => {
                let (ident, end) = read_ident(&chars, i + 1)?;
                i = end;
                steps.push(if ident == "Parent" { Step::Parent } else { Step::Child(ident) });
            }
            '[' => {
                i += 1;
                let quote = *chars.get(i)?;
                if quote != '"' && quote != '\'' {
                    return None;
                }
                i += 1;
                let mut name = String::new();
                loop {
                    let c = *chars.get(i)?;
                    if c == '\\' {
                        // JSON.stringify escapes (mirror shims). Anything
                        // fancier (\uXXXX) bails; the file is left alone.
                        let n = *chars.get(i + 1)?;
                        match n {
                            '\\' | '"' | '\'' | '/' => {
                                name.push(n);
                                i += 2;
                            }
                            _ => return None,
                        }
                    } else if c == quote {
                        i += 1;
                        break;
                    } else {
                        name.push(c);
                        i += 1;
                    }
                }
                if *chars.get(i)? != ']' {
                    return None;
                }
                i += 1;
                steps.push(Step::Child(name));
            }
            c if c.is_whitespace() => i += 1,
            _ => return None,
        }
    }
    Some(steps)
}

/// One require hop: map `script…` from the link file's DataModel position to
/// the filesystem. A link named init.lua(u) IS its folder (folder module:
/// `script` = the directory); any other file is itself.
fn resolve_one(link_file: &Path, expr: &str) -> Option<PathBuf> {
    let steps = parse_steps(expr)?;
    let file_name = link_file.file_name()?.to_str()?;
    let is_folder_module = file_name == "init.lua" || file_name == "init.luau";
    // `node` is the fs object backing the current Instance: a directory for
    // folders/folder-modules, a file for file modules. Parent semantics are
    // the same for both: the containing directory('s parent).
    let mut node = if is_folder_module {
        link_file.parent()?.to_path_buf()
    } else {
        link_file.to_path_buf()
    };
    for step in steps {
        node = match step {
            Step::Parent => node.parent()?.to_path_buf(),
            Step::Child(name) => child_node(&node, &name)?,
        };
    }
    // The final Instance must be a module: a file, or a folder with an init.
    if node.is_dir() {
        ["init.lua", "init.luau"] // The case where the folder is actually a module
            .iter()
            .map(|init| node.join(init))
            .find(|p| p.is_file())
    } else if node.is_file() { // Module is literally a module
        Some(node)
    } else {
        None
    }
}

/// A child Instance under a directory: a subdirectory or a `Name.lua(u)`
/// file. Pointer exprs URL-encode segment names (plan.rs) while mirror shims
/// don't — try the raw name first, then its URL-decoded form.
fn child_node(dir: &Path, name: &str) -> Option<PathBuf> {
    let mut candidates = vec![name.to_string()];
    if name.contains('%') {
        if let Ok(decoded) = urlencoding::decode(name) {
            if decoded != name {
                candidates.push(decoded.into_owned());
            }
        }
    }
    for candidate in candidates {
        let sub = dir.join(&candidate);
        if sub.is_dir() {
            return Some(sub);
        }
        for ext in ["lua", "luau"] {
            let file = dir.join(format!("{candidate}.{ext}"));
            if file.is_file() {
                return Some(file);
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Luau source scanning
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
struct ExportedType {
    name: String,
    /// Inner text of the generic parameter list (`T, U = any?`), None for a
    /// non-generic type.
    generics: Option<String>,
}

// Shared scanning primitives: every pass below walks `&[char]` with an
// index, and all string/escape handling lives in skip_string alone.

fn is_ident_char(c: char) -> bool {
    c.is_alphanumeric() || c == '_'
}

/// Read the identifier starting at chars[start]; returns it and one-past-end.
fn read_ident(chars: &[char], start: usize) -> Option<(String, usize)> {
    let mut end = start;
    while end < chars.len() && is_ident_char(chars[end]) {
        end += 1;
    }
    (end > start && !chars[start].is_ascii_digit())
        .then(|| (chars[start..end].iter().collect(), end))
}

/// One past the end of the string literal starting at chars[i] — short (`"…"` /
/// `'…'`, escape-aware) or long (`[=*[…]=*]`) — or None when chars[i] starts no
/// string. Unterminated strings run to the end of input.
fn skip_string(chars: &[char], i: usize) -> Option<usize> {
    match chars.get(i) {
        Some(&quote @ ('"' | '\'')) => {
            let mut j = i + 1;
            while j < chars.len() {
                match chars[j] {
                    '\\' => j += 2,
                    c if c == quote => return Some(j + 1),
                    _ => j += 1,
                }
            }
            Some(chars.len())
        }
        Some('[') => long_bracket_level(chars, i).map(|level| long_bracket_end(chars, i, level)),
        _ => None,
    }
}

/// Blank out comments (line and long-bracket) while leaving string literals
/// intact, so declaration scanning never matches commented-out code.
/// Newlines survive so blanked regions stay line-shaped.
fn strip_comments(src: &str) -> String {
    let chars: Vec<char> = src.chars().collect();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    while i < chars.len() {
        if let Some(end) = skip_string(&chars, i) {
            out.extend(&chars[i..end]);
            i = end;
        } else if chars[i] == '-' && chars.get(i + 1) == Some(&'-') {
            let end = match long_bracket_level(&chars, i + 2) {
                Some(level) => long_bracket_end(&chars, i + 2, level),
                None => {
                    let mut j = i;
                    while j < chars.len() && chars[j] != '\n' {
                        j += 1;
                    }
                    j
                }
            };
            out.extend(chars[i..end].iter().map(|&c| if c == '\n' { '\n' } else { ' ' }));
            i = end;
        } else {
            out.push(chars[i]);
            i += 1;
        }
    }
    out
}

/// Is chars[i] the opening of a long bracket `[=*[`? Returns its level.
fn long_bracket_level(chars: &[char], i: usize) -> Option<usize> {
    if chars.get(i) != Some(&'[') {
        return None;
    }
    let mut j = i + 1;
    let mut level = 0;
    while chars.get(j) == Some(&'=') {
        level += 1;
        j += 1;
    }
    if chars.get(j) == Some(&'[') { Some(level) } else { None }
}

/// Index one past the closing `]=*]` of the long bracket opening at `open`,
/// or the end of input when unterminated.
fn long_bracket_end(chars: &[char], open: usize, level: usize) -> usize {
    let mut i = open + level + 2;
    while i < chars.len() {
        if chars[i] == ']' {
            let mut j = i + 1;
            let mut eq = 0;
            while chars.get(j) == Some(&'=') {
                eq += 1;
                j += 1;
            }
            if eq == level && chars.get(j) == Some(&']') {
                return j + 1;
            }
        }
        i += 1;
    }
    chars.len()
}

/// Collect `export type Name<…> =` declarations from comment-stripped source.
/// String literals survive comment stripping (singleton-type defaults need
/// them), so the scan steps over them here.
fn extract_exports(cleaned: &str) -> Vec<ExportedType> {
    let chars: Vec<char> = cleaned.chars().collect();
    let mut exports: Vec<ExportedType> = Vec::new();
    let mut seen: HashSet<String> = HashSet::new();
    let mut scan = 0; // where the keyword hunt currently is
    while scan < chars.len() {
        if let Some(string_end) = skip_string(&chars, scan) {
            scan = string_end;
            continue;
        }
        // A declaration is the sequence `export type Name`, each word at an
        // identifier boundary. Any mismatch moves the hunt forward one char.
        if chars[scan] != 'e'
            || (scan > 0 && is_ident_char(chars[scan - 1]))
            || !word_at(&chars, scan, "export")
        {
            scan += 1;
            continue;
        }
        let type_kw = skip_ws(&chars, scan + "export".len());
        if type_kw == scan + "export".len() || !word_at(&chars, type_kw, "type") {
            scan += 1;
            continue;
        }
        let name_start = skip_ws(&chars, type_kw + "type".len());
        if name_start == type_kw + "type".len() {
            scan += 1;
            continue;
        }
        let Some((name, after_name)) = read_ident(&chars, name_start) else {
            scan += 1;
            continue;
        };
        // `cursor` walks the rest of the declaration: an optional generic
        // parameter list, then the `=` that makes it a real declaration.
        let mut cursor = skip_ws(&chars, after_name);
        let generics = if chars.get(cursor) == Some(&'<') {
            match capture_generics(&chars, cursor) {
                Some((params, after_generics)) => {
                    cursor = after_generics;
                    if params.trim().is_empty() { None } else { Some(params) }
                }
                None => {
                    // Unbalanced `<…`: skip it, keep hunting.
                    scan = cursor + 1;
                    continue;
                }
            }
        } else {
            None
        };
        // Only an actual declaration (`= …` follows) counts.
        let equals_at = skip_ws(&chars, cursor);
        if chars.get(equals_at) == Some(&'=')
            && chars.get(equals_at + 1) != Some(&'=')
            && seen.insert(name.clone())
        {
            exports.push(ExportedType { name, generics });
        }
        scan = cursor;
    }
    exports
}

/// Does the identifier-boundary word `word` start at chars[i]?
fn word_at(chars: &[char], i: usize, word: &str) -> bool {
    i + word.len() <= chars.len()
        && chars[i..i + word.len()].iter().copied().eq(word.chars())
        && chars.get(i + word.len()).map_or(true, |&c| !is_ident_char(c))
}

fn skip_ws(chars: &[char], mut i: usize) -> usize {
    while i < chars.len() && chars[i].is_whitespace() {
        i += 1;
    }
    i
}

/// Capture the inner text of a balanced `<…>` starting at chars[open]. `->`
/// arrows and string literals inside (e.g. singleton-type defaults) don't
/// count toward nesting.
fn capture_generics(chars: &[char], open: usize) -> Option<(String, usize)> {
    let mut depth = 1usize;
    let mut i = open + 1;
    while i < chars.len() {
        if let Some(end) = skip_string(chars, i) {
            i = end;
            continue;
        }
        match chars[i] {
            '<' => depth += 1,
            '>' if chars[i - 1] != '-' => {
                depth -= 1;
                if depth == 0 {
                    return Some((chars[open + 1..i].iter().collect(), i + 1));
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// Split on a separator at bracket depth 0 (over `<>()[]{}`), string-aware.
fn split_top_level(inner: &str, sep: char) -> Vec<String> {
    let chars: Vec<char> = inner.chars().collect();
    let mut parts = Vec::new();
    let mut current = String::new();
    let mut depth = 0usize;
    let mut i = 0;
    while i < chars.len() {
        if let Some(end) = skip_string(&chars, i) {
            current.extend(&chars[i..end]);
            i = end;
            continue;
        }
        let c = chars[i];
        match c {
            '<' | '(' | '[' | '{' => depth += 1,
            '>' if i > 0 && chars[i - 1] == '-' => {} // `->` arrow
            '>' | ')' | ']' | '}' => depth = depth.saturating_sub(1),
            _ => {}
        }
        if c == sep && depth == 0 {
            parts.push(current.trim().to_string());
            current.clear();
        } else {
            current.push(c);
        }
        i += 1;
    }
    if !current.trim().is_empty() {
        parts.push(current.trim().to_string());
    }
    parts
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/// Render the patched link module. The require expression is reused verbatim
/// from the generated file; only the shape around it changes.
fn render(header: &str, expr: &str, exports: &[ExportedType]) -> String {
    if exports.is_empty() {
        return format!("{header}\nreturn require({expr})\n");
    }
    let exported_names: HashSet<String> = exports.iter().map(|e| e.name.clone()).collect();
    let mut out = format!("{header}\nlocal {LOCAL_NAME} = require({expr})\n");
    for export in exports {
        match &export.generics {
            None => {
                out.push_str(&format!(
                    "export type {} = {LOCAL_NAME}.{}\n",
                    export.name, export.name
                ));
            }
            Some(inner) => {
                let Some((decls, args)) = render_params(inner, &exported_names) else {
                    // Unparseable generics: skip just this type.
                    continue;
                };
                out.push_str(&format!(
                    "export type {}<{}> = {LOCAL_NAME}.{}<{}>\n",
                    export.name, decls, export.name, args
                ));
            }
        }
    }
    out.push_str(&format!("return {LOCAL_NAME}\n"));
    out
}

/// Turn a generic parameter list into the re-export's declaration side
/// (params with defaults, module-local defaults qualified) and application
/// side (bare param names, `...` kept for type packs).
fn render_params(inner: &str, exported: &HashSet<String>) -> Option<(String, String)> {
    let raw = split_top_level(inner, ',');
    if raw.is_empty() {
        return None;
    }
    let mut names: HashSet<String> = HashSet::new();
    let mut parsed: Vec<(String, bool, Option<String>)> = Vec::new();
    for param in &raw {
        let (name, is_pack, default) = parse_param(param)?;
        names.insert(name.clone());
        parsed.push((name, is_pack, default));
    }
    let mut decls = Vec::new();
    let mut args = Vec::new();
    for (name, is_pack, default) in parsed {
        let dots = if is_pack { "..." } else { "" };
        match default {
            Some(default) => decls.push(format!(
                "{name}{dots} = {}",
                qualify_default(&default, exported, &names)
            )),
            None => decls.push(format!("{name}{dots}")),
        }
        args.push(format!("{name}{dots}"));
    }
    Some((decls.join(", "), args.join(", ")))
}

/// Parse one generic parameter: `T`, `T...`, `T = default`, `T... = default`.
fn parse_param(param: &str) -> Option<(String, bool, Option<String>)> {
    let chars: Vec<char> = param.trim().chars().collect();
    let (name, mut i) = read_ident(&chars, 0)?;
    i = skip_ws(&chars, i);
    let is_pack = matches!(chars.get(i..i + 3), Some(['.', '.', '.']));
    if is_pack {
        i = skip_ws(&chars, i + 3);
    }
    let default = match chars.get(i) {
        None => None,
        Some(&'=') if chars.get(i + 1) != Some(&'=') => {
            let text: String = chars[i + 1..].iter().collect();
            let text = text.trim();
            if text.is_empty() {
                return None;
            }
            Some(text.to_string())
        }
        _ => return None,
    };
    Some((name, is_pack, default))
}

/// Qualify references to the target module's own exported types inside a
/// generic default (`Signal<number>` -> `MODULE.Signal<number>`), leaving
/// generic parameter names, builtins, and already-qualified names alone.
fn qualify_default(default: &str, exported: &HashSet<String>, params: &HashSet<String>) -> String {
    let chars: Vec<char> = default.chars().collect();
    let mut out = String::with_capacity(default.len());
    // Last non-whitespace char emitted: a preceding `.` (or ident char)
    // means the next identifier is already qualified / mid-name.
    let mut prev_sig: Option<char> = None;
    let mut i = 0;
    while i < chars.len() {
        if let Some(end) = skip_string(&chars, i) {
            out.extend(&chars[i..end]);
            prev_sig = chars.get(end - 1).copied();
            i = end;
            continue;
        }
        let qualifiable = prev_sig != Some('.') && !matches!(prev_sig, Some(p) if is_ident_char(p));
        if let Some((word, end)) = read_ident(&chars, i).filter(|_| qualifiable) {
            if exported.contains(&word) && !params.contains(&word) {
                out.push_str(LOCAL_NAME);
                out.push('.');
            }
            out.push_str(&word);
            prev_sig = chars.get(end - 1).copied();
            i = end;
            continue;
        }
        let c = chars[i];
        out.push(c);
        if !c.is_whitespace() {
            prev_sig = Some(c);
        }
        i += 1;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(tag: &str) -> PathBuf {
        let base = std::env::temp_dir().join(format!("forest-typelink-{}-{}", tag, std::process::id()));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(&base).unwrap();
        base
    }

    const WRAPPER_HEADER: &str =
        "--Generated by the forest wally mirror. Re-exports the package's root module.";
    const STUB_HEADER: &str = "--Generated by the forest wally mirror. Wally-style sibling link.";

    /// Replica of the mirrored matrix/vector layout from a real install:
    /// wrapper init.lua, sibling stub, real module in src/, nested dep.
    fn write_matrix_tree(mount: &Path) {
        let matrix = mount.join("matrix");
        fs::create_dir_all(matrix.join("src")).unwrap();
        fs::create_dir_all(matrix.join("Packages").join("Vector")).unwrap();
        fs::write(
            matrix.join("init.lua"),
            format!("{WRAPPER_HEADER}\nreturn require(script[\"src\"])\n"),
        )
        .unwrap();
        fs::write(
            matrix.join("Vector.lua"),
            format!("{STUB_HEADER}\nreturn require(script.Parent.Packages[\"Vector\"])\n"),
        )
        .unwrap();
        fs::write(
            matrix.join("src").join("init.lua"),
            "--!strict\nlocal Vector = require(script.Parent.Vector)\nexport type Vector = Vector.Vector\nexport type Matrix = {\n\tDimensions: Vector,\n}\nreturn {}\n",
        )
        .unwrap();
        fs::write(
            matrix.join("Packages").join("Vector").join("init.lua"),
            "--!strict\nexport type Vector = {\n\tSize: number,\n}\nreturn {}\n",
        )
        .unwrap();
    }

    #[test]
    fn wrapper_and_stub_reexport_their_targets_types() {
        let mount = fixture("matrix");
        write_matrix_tree(&mount);

        relink_types(&mount);

        let wrapper = fs::read_to_string(mount.join("matrix").join("init.lua")).unwrap();
        assert!(wrapper.starts_with(WRAPPER_HEADER), "header must survive: {wrapper}");
        assert!(wrapper.contains("local MODULE = require(script[\"src\"])"));
        assert!(wrapper.contains("export type Vector = MODULE.Vector"));
        assert!(wrapper.contains("export type Matrix = MODULE.Matrix"));
        assert!(wrapper.ends_with("return MODULE\n"));

        let stub = fs::read_to_string(mount.join("matrix").join("Vector.lua")).unwrap();
        assert!(stub.starts_with(STUB_HEADER));
        assert!(stub.contains("local MODULE = require(script.Parent.Packages[\"Vector\"])"));
        assert!(stub.contains("export type Vector = MODULE.Vector"));

        // Real modules are never touched.
        let real = fs::read_to_string(mount.join("matrix").join("src").join("init.lua")).unwrap();
        assert!(real.starts_with("--!strict"));
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn relink_is_idempotent() {
        let mount = fixture("idempotent");
        write_matrix_tree(&mount);

        relink_types(&mount);
        let first = fs::read_to_string(mount.join("matrix").join("init.lua")).unwrap();
        relink_types(&mount);
        let second = fs::read_to_string(mount.join("matrix").join("init.lua")).unwrap();

        assert_eq!(first, second);
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn pointer_resolves_through_a_mirror_wrapper_chain() {
        // Knit's nested dep X got hoisted: pointer -> X's wrapper -> X/src.
        let mount = fixture("chain");
        let pointer_dir = mount.join("Knit").join("Packages").join("X");
        fs::create_dir_all(&pointer_dir).unwrap();
        fs::write(
            pointer_dir.join("init.lua"),
            format!("{POINTER_HEADER}\nreturn require(script.Parent.Parent.Parent['X'])"),
        )
        .unwrap();
        let x = mount.join("X");
        fs::create_dir_all(x.join("src")).unwrap();
        fs::write(x.join("init.lua"), format!("{WRAPPER_HEADER}\nreturn require(script[\"src\"])\n")).unwrap();
        fs::write(x.join("src").join("init.lua"), "export type Foo = { n: number }\nreturn {}\n").unwrap();

        relink_types(&mount);

        let pointer = fs::read_to_string(pointer_dir.join("init.lua")).unwrap();
        assert!(pointer.starts_with(POINTER_HEADER));
        assert!(pointer.contains("local MODULE = require(script.Parent.Parent.Parent['X'])"));
        assert!(pointer.contains("export type Foo = MODULE.Foo"));
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn any_future_forest_generated_header_is_recognized() {
        // The mirror contract is the `--Generated by the forest ` prefix
        // only — a link flavor that doesn't exist yet must still relink.
        let mount = fixture("future");
        let dir = mount.join("Thing");
        fs::create_dir_all(dir.join("src")).unwrap();
        fs::write(
            dir.join("init.lua"),
            "--Generated by the forest quantum linker.\nreturn require(script[\"src\"])\n",
        )
        .unwrap();
        fs::write(dir.join("src").join("init.lua"), "export type Thing = number\nreturn {}\n").unwrap();

        relink_types(&mount);

        let link = fs::read_to_string(dir.join("init.lua")).unwrap();
        assert!(link.starts_with("--Generated by the forest quantum linker."));
        assert!(link.contains("export type Thing = MODULE.Thing"), "{link}");
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn typeless_target_normalizes_to_the_plain_form() {
        let mount = fixture("typeless");
        let dir = mount.join("Promise");
        fs::create_dir_all(dir.join("src")).unwrap();
        fs::write(dir.join("init.lua"), format!("{WRAPPER_HEADER}\nreturn require(script[\"src\"])\n")).unwrap();
        fs::write(dir.join("src").join("init.lua"), "return { ok = true }\n").unwrap();

        relink_types(&mount);

        assert_eq!(
            fs::read_to_string(dir.join("init.lua")).unwrap(),
            format!("{WRAPPER_HEADER}\nreturn require(script[\"src\"])\n")
        );
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn broken_target_leaves_the_link_untouched() {
        let mount = fixture("broken");
        let dir = mount.join("Ghost");
        fs::create_dir_all(&dir).unwrap();
        let original = format!("{POINTER_HEADER}\nreturn require(script.Parent.Parent['Nowhere'])");
        fs::write(dir.join("init.lua"), &original).unwrap();

        relink_types(&mount);

        assert_eq!(fs::read_to_string(dir.join("init.lua")).unwrap(), original);
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn generics_defaults_and_packs_reexport_correctly() {
        let mount = fixture("generics");
        let dir = mount.join("remote");
        fs::create_dir_all(dir.join("src")).unwrap();
        fs::write(dir.join("init.lua"), format!("{WRAPPER_HEADER}\nreturn require(script[\"src\"])\n")).unwrap();
        fs::write(
            dir.join("src").join("init.lua"),
            concat!(
                "export type Signal<T> = { fire: (T) -> () }\n",
                "export type State<T = any?> = { value: T }\n",
                "export type Pack<T...> = (T...) -> ()\n",
                "export type Fn<F = () -> ()> = { f: F }\n",
                "export type Pair<T = Signal<number>> = { t: T }\n",
                "return {}\n",
            ),
        )
        .unwrap();

        relink_types(&mount);

        let link = fs::read_to_string(dir.join("init.lua")).unwrap();
        assert!(link.contains("export type Signal<T> = MODULE.Signal<T>"), "{link}");
        assert!(link.contains("export type State<T = any?> = MODULE.State<T>"), "{link}");
        assert!(link.contains("export type Pack<T...> = MODULE.Pack<T...>"), "{link}");
        assert!(link.contains("export type Fn<F = () -> ()> = MODULE.Fn<F>"), "{link}");
        assert!(
            link.contains("export type Pair<T = MODULE.Signal<number>> = MODULE.Pair<T>"),
            "module-local default types must be qualified: {link}"
        );
        let _ = fs::remove_dir_all(&mount);
    }

    #[test]
    fn commented_out_and_string_exports_are_ignored() {
        let cleaned = strip_comments(concat!(
            "-- export type Line = number\n",
            "--[[\nexport type Block = number\n]]\n",
            "local s = \"export type InString = number\"\n",
            "export type Real = number\n",
        ));
        let exports = extract_exports(&cleaned);
        assert_eq!(exports.len(), 1);
        assert_eq!(exports[0].name, "Real");
    }

    #[test]
    fn multiline_generic_declarations_parse() {
        let exports = extract_exports("export type Handler<\n\tT,\n\tU = any?\n> = (T) -> U\n");
        assert_eq!(exports.len(), 1);
        assert_eq!(exports[0].name, "Handler");
        let (decls, args) =
            render_params(exports[0].generics.as_ref().unwrap(), &HashSet::new()).unwrap();
        assert_eq!(decls, "T, U = any?");
        assert_eq!(args, "T, U");
    }

    #[test]
    fn type_usage_without_declaration_is_not_collected() {
        // `export type` must be followed by `=` at the right spot; a mention
        // inside another declaration's body must not double-collect.
        let exports = extract_exports("export type A = { chars: B }\nlocal exporter = 1\n");
        assert_eq!(exports.len(), 1);
        assert_eq!(exports[0].name, "A");
    }
}
