//! UEFN (Verse) platform knowledge.
//!
//! Everything Verse-specific the CLI needs: project discovery, the scope →
//! Verse-identifier mapping, package-name validation, marker-file
//! generation, the running-editor probe, and the root-definition lint.
//! Identifier rules come from the shared contract (see src/contracts.rs);
//! the layout/marker semantics are compiler-verified in forest-backend
//! docs/uefn-adapter.md (§4–§7).

pub mod init;
pub mod install;
pub mod plan;
pub mod publish;

use anyhow::{anyhow, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// First line of every CLI-generated `.verse` marker file. Delete-by-header
/// is the only license to remove a `.verse` file, mirroring the Roblox
/// pointer-file convention - KEEP THIS STRING STABLE FOREVER once shipped,
/// or old markers become undeletable orphans.
pub const MARKER_HEADER: &str = "# Generated by Forest Package Manager. Do not edit.";

pub struct UefnProject {
    pub project_root: PathBuf,
    /// The <Name>.uefnproject file.
    pub project_file: PathBuf,
    pub content_dir: PathBuf,
}

fn find_file_with_extension(dir: &Path, ext: &str) -> Option<PathBuf> {
    fs::read_dir(dir).ok()?.flatten().find_map(|entry| {
        let path = entry.path();
        let is_match = path.is_file()
            && path.extension().map(|e| e.eq_ignore_ascii_case(ext)).unwrap_or(false);
        is_match.then_some(path)
    })
}

/// Walk upward from `start` looking for a directory containing a
/// `*.uefnproject` file (the UEFN project root).
pub fn find_project(start: &Path) -> Option<UefnProject> {
    let mut dir = Some(start);
    while let Some(current) = dir {
        if let Some(project_file) = find_file_with_extension(current, "uefnproject") {
            return Some(UefnProject {
                project_root: current.to_path_buf(),
                content_dir: current.join("Content"),
                project_file,
            });
        }
        dir = current.parent();
    }
    None
}

/// The project's Verse root path (e.g. "/invaliddomain/ForestTest") from the
/// `.uplugin` next to the `.uefnproject`. MUTABLE - the domain becomes real
/// on first publish and the project can be renamed - which is why markers
/// are regenerated on every install.
pub fn read_verse_path(project: &UefnProject) -> Result<String> {
    let uplugin = find_file_with_extension(&project.project_root, "uplugin")
        .ok_or_else(|| anyhow!("No .uplugin file found in {}", project.project_root.display()))?;
    let parsed: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(&uplugin)
            .with_context(|| format!("Failed to read {}", uplugin.display()))?,
    )
    .with_context(|| format!("Failed to parse {}", uplugin.display()))?;
    parsed
        .get("VersePath")
        .and_then(serde_json::Value::as_str)
        .map(str::to_string)
        .ok_or_else(|| anyhow!("No VersePath in {}", uplugin.display()))
}

/// The UEFN compatibilityVersion the project is on (a STRING, e.g. "41.20").
/// Recorded on published versions for display/warn only.
pub fn read_compat_version(project: &UefnProject) -> Option<String> {
    let parsed: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&project.project_file).ok()?).ok()?;
    parsed
        .get("compatibilityVersion")
        .and_then(serde_json::Value::as_str)
        .map(str::to_string)
}

/// Contract scope mapping: '-' -> '_', then a '_' prefix when the result
/// would start with a digit or be a Verse reserved word. Injective because
/// kebab slugs can never contain underscores.
pub fn map_scope_to_verse_identifier(scope: &str) -> String {
    let mut mapped = scope.replace('-', "_");
    let digit_led = mapped.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false);
    if digit_led || crate::contracts::verse_rules().reserved_words.iter().any(|w| w == &mapped) {
        mapped.insert(0, '_');
    }
    mapped
}

/// UEFN package names are NEVER auto-renamed: they must be valid,
/// non-reserved Verse identifiers as typed (reserved check is exact and
/// case-sensitive - Verse keywords are lowercase, so `Module` is fine).
pub fn validate_uefn_package_name(name: &str) -> Result<(), String> {
    let mut chars = name.chars();
    let head_ok = chars
        .next()
        .map(|c| c.is_ascii_alphabetic() || c == '_')
        .unwrap_or(false);
    if !head_ok || !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err(format!(
            "Invalid package name \"{}\" for UEFN. Names become Verse module identifiers: \
             they must start with a letter or underscore and contain only letters, digits, and underscores (no hyphens).",
            name
        ));
    }
    if crate::contracts::verse_rules().reserved_words.iter().any(|w| w == name) {
        return Err(format!("Invalid package name \"{}\": it is a Verse reserved word.", name));
    }
    Ok(())
}

pub enum MarkerAccess {
    /// Direct dependencies + authored packages + every scope-level marker.
    Public,
    /// Transitive-only dependencies: visible inside the mount subtree
    /// (dependents can import them) but hidden from consumer code -
    /// compiler-level phantom-dependency prevention.
    Scoped { subtree: String },
}

/// The exact marker forms verified against the Verse compiler (evidence log
/// in docs/uefn-adapter.md): `X<public> := module {}` /
/// `X<scoped {/path/ForestPackages}> := module {}`.
pub fn marker_content(ident: &str, access: &MarkerAccess) -> String {
    let declaration = match access {
        MarkerAccess::Public => format!("{}<public> := module {{}}", ident),
        MarkerAccess::Scoped { subtree } => {
            format!("{}<scoped {{{}}}> := module {{}}", ident, subtree)
        }
    };
    format!("{}\n{}\n", MARKER_HEADER, declaration)
}

/// A `.verse` file is Forest's to delete only when its first line is the
/// marker header (mirror of receipts::is_pointer_dir).
pub fn is_forest_marker(path: &Path) -> bool {
    fs::read_to_string(path)
        .map(|text| text.lines().next() == Some(MARKER_HEADER))
        .unwrap_or(false)
}

/// UEFN only discovers new files at project open, and the open editor holds
/// locks on Content/ folders. Renaming the Forest-owned mount is a cheap
/// probe: rename fails => the editor is open and the user needs a reopen for
/// new packages to be seen. Heuristic by design (an AV scan can
/// false-positive - the cost is only an extra instruction line).
pub fn is_editor_running(mount: &Path) -> Result<bool> {
    if !mount.exists() {
        return Ok(false);
    }
    let probe = mount.with_file_name(format!(
        "{}.forest-probe",
        mount.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default()
    ));
    if fs::rename(mount, &probe).is_err() {
        return Ok(true);
    }
    // Never leave the tree renamed: retry the rename-back, then fail loudly
    // with the exact manual fix.
    for attempt in 0..5 {
        match fs::rename(&probe, mount) {
            Ok(()) => return Ok(false),
            Err(_) if attempt < 4 => std::thread::sleep(std::time::Duration::from_millis(100)),
            Err(err) => {
                return Err(anyhow!(
                    "Editor probe could not restore the packages folder: {}. \
                     Manually rename \"{}\" back to \"{}\".",
                    err,
                    probe.display(),
                    mount.display()
                ))
            }
        }
    }
    unreachable!()
}

/// Warn-only lint (docs/uefn-adapter.md §6/§7): function DEFINITIONS in
/// root-level `.verse` files collide with any installed package exporting
/// the same name + signature - at any access level, at definition site.
/// Heuristic line scan: an unindented `Identifier`, optionally followed by
/// `<specifier>` groups, whose next non-space char is `(`. `using { ... }`
/// and `X := class(...)` don't match by construction.
pub fn lint_root_function_defs(content_dir: &Path) -> Vec<String> {
    let mut warnings = Vec::new();
    let Ok(entries) = fs::read_dir(content_dir) else {
        return warnings;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let is_verse = path.is_file()
            && path.extension().map(|e| e.eq_ignore_ascii_case("verse")).unwrap_or(false);
        if !is_verse {
            continue;
        }
        let Ok(text) = fs::read_to_string(&path) else { continue };
        for line in text.lines() {
            if let Some(name) = detect_function_def(line) {
                warnings.push(format!(
                    "{}: root-level function \"{}\" is risky. Any installed package exporting the \
                     same name and signature will fail the Verse build (definitions collide across \
                     ancestor scopes). Move it into a folder module (e.g. Src/) instead.",
                    path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
                    name
                ));
            }
        }
    }
    warnings
}

fn detect_function_def(line: &str) -> Option<&str> {
    let bytes = line.as_bytes();
    let first = *bytes.first()?;
    if !(first.is_ascii_alphabetic() || first == b'_') {
        return None; // indented, comment, or non-identifier line
    }
    let mut i = 1;
    while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
        i += 1;
    }
    let name_end = i;
    // Zero or more <...> specifier groups directly after the identifier.
    while i < bytes.len() && bytes[i] == b'<' {
        match line[i..].find('>') {
            Some(close) => i += close + 1,
            None => return None,
        }
    }
    while i < bytes.len() && bytes[i] == b' ' {
        i += 1;
    }
    (i < bytes.len() && bytes[i] == b'(').then(|| &line[..name_end])
}

/// Does `start` look like a UEFN project? (A `*.uefnproject` in the
/// directory or any ancestor.)
pub fn detect_project(start: &Path) -> bool {
    find_project(start).is_some()
}

/// Manifest discovery: the UEFN manifest lives in the project's Content
/// folder, so commands run from the project root (or any subdir) can be
/// pointed at it. Returns None when there's no project or no manifest.
pub fn discover_manifest_dir(start: &Path) -> Option<PathBuf> {
    let project = find_project(start)?;
    if project.content_dir.join("forest.json").exists() {
        Some(project.content_dir)
    } else {
        None
    }
}

pub(crate) fn dir_name(path: &Path) -> String {
    path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default()
}

/// Is the ancestor `generations` levels above `cwd` the packages mount?
/// (1 = parent is the mount: a scope dir; 2 = grandparent: a package dir.)
pub(crate) fn ancestor_is_mount(cwd: &Path, generations: usize) -> bool {
    let mount_name = &crate::contracts::verse_rules().packages_mount;
    cwd.ancestors()
        .nth(generations)
        .and_then(|p| p.file_name())
        .map(|n| n.to_string_lossy() == *mount_name)
        .unwrap_or(false)
}

/// Workspace resolution roots (docs/uefn-adapter.md §7 authoring): the
/// PROJECT owns dependency resolution. Roots = the Content manifest's deps
/// merged with every AUTHORED package's declared deps, so a package's
/// `using { ForestPackages.X.Y }` imports are installed at the shared mount
/// no matter which manifest declared them, and the single-version rule
/// spans the whole workspace. When one dependency is declared with
/// different requirements, both must hold (Rust semver treats comma as AND)
/// and an impossible combination fails at resolve time.
pub fn gather_workspace_roots(
    project: &UefnProject,
) -> anyhow::Result<std::collections::HashMap<String, crate::lockfile_solver::DepSpec>> {
    use crate::utils::normalize_forest_deps;

    fn merge(
        merged: &mut std::collections::HashMap<String, crate::lockfile_solver::DepSpec>,
        roots: std::collections::HashMap<String, crate::lockfile_solver::DepSpec>,
    ) {
        for (name, spec) in roots {
            let existing = merged
                .iter_mut()
                .find(|(key, _)| key.eq_ignore_ascii_case(&name))
                .map(|(_, value)| value);
            match existing {
                Some(existing) => {
                    // AND the constraints, skipping ones already present
                    // (the joined string is itself comma-separated).
                    let already = existing.version.split(',').any(|part| part.trim() == spec.version.trim());
                    if !already {
                        existing.version = format!("{}, {}", existing.version, spec.version);
                    }
                }
                None => {
                    merged.insert(name, spec);
                }
            }
        }
    }

    let mut merged = std::collections::HashMap::new();

    let project_manifest = project.content_dir.join("forest.json");
    if let Ok(text) = fs::read_to_string(&project_manifest) {
        if let Ok(value) = serde_json::from_str::<serde_json::Value>(&text) {
            merge(&mut merged, normalize_forest_deps(&value));
        }
    }

    let mount_name = &crate::contracts::verse_rules().packages_mount;
    let mount = project.content_dir.join(mount_name);
    let tree = crate::receipts::scan_flat(&mount, mount_name, MARKER_HEADER);
    for authored in &tree.authored {
        let manifest = mount.join(&authored.scope_dir).join(&authored.name_dir).join("forest.json");
        if let Ok(text) = fs::read_to_string(&manifest) {
            if let Ok(value) = serde_json::from_str::<serde_json::Value>(&text) {
                merge(&mut merged, normalize_forest_deps(&value));
            }
        }
    }

    Ok(merged)
}

/// The Verse import snippet printed after adding a package: the dotted
/// relative form (prefix-free), plus the collision-proof qualified fallback.
pub fn install_snippet(scope: &str, name: &str) -> String {
    let mount = &crate::contracts::verse_rules().packages_mount;
    let mapped = map_scope_to_verse_identifier(&scope.to_lowercase());
    format!(
        "Add to your Verse file:\n      using {{ {mount}.{mapped}.{name} }}\n   On a name conflict, qualify call sites instead: ({mount}.{mapped}.{name}:)Fn(...)"
    )
}

/// Why `-a` is rejected on UEFN: aliases would need per-symbol re-export
/// shims Verse doesn't have.
pub fn alias_error() -> String {
    format!(
        "Aliases aren't supported on UEFN. Verse imports are already scope-namespaced; \
         disambiguate call sites with qualified access instead: ({}.scope.name:)Fn(...)",
        crate::contracts::verse_rules().packages_mount
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct VerseVectors {
        scope_mapping: Vec<(String, String)>,
        valid_package_names: Vec<String>,
        invalid_package_names: Vec<String>,
        reserved_package_names: Vec<String>,
    }

    fn vectors() -> VerseVectors {
        serde_json::from_str(include_str!("../../shared/contracts/verse-rules.vectors.json"))
            .expect("verse-rules.vectors.json failed to parse")
    }

    #[test]
    fn contract_scope_mapping_vectors_all_pass() {
        for (input, expected) in vectors().scope_mapping {
            assert_eq!(map_scope_to_verse_identifier(&input), expected, "{}", input);
        }
    }

    #[test]
    fn contract_package_name_vectors_all_pass() {
        let v = vectors();
        for name in v.valid_package_names {
            assert!(validate_uefn_package_name(&name).is_ok(), "{}", name);
        }
        for name in v.invalid_package_names {
            assert!(validate_uefn_package_name(&name).is_err(), "{:?}", name);
        }
        for name in v.reserved_package_names {
            let err = validate_uefn_package_name(&name).unwrap_err();
            assert!(err.contains("reserved word"), "{}: {}", name, err);
        }
    }

    #[test]
    fn marker_content_matches_the_compiled_forms() {
        assert_eq!(
            marker_content("TestScope", &MarkerAccess::Public),
            format!("{}\nTestScope<public> := module {{}}\n", MARKER_HEADER)
        );
        assert_eq!(
            marker_content(
                "MathUtil",
                &MarkerAccess::Scoped { subtree: "/invaliddomain/ForestTest/ForestPackages".into() }
            ),
            format!(
                "{}\nMathUtil<scoped {{/invaliddomain/ForestTest/ForestPackages}}> := module {{}}\n",
                MARKER_HEADER
            )
        );
    }

    fn temp_project(tag: &str) -> UefnProject {
        let base = std::env::temp_dir().join(format!("forest-uefn-{}-{}", tag, std::process::id()));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(base.join("Content")).unwrap();
        fs::write(
            base.join("MyIsland.uefnproject"),
            r#"{ "title": "MyIsland", "compatibilityVersion": "41.20" }"#,
        )
        .unwrap();
        fs::write(base.join("MyIsland.uplugin"), r#"{ "VersePath": "/invaliddomain/MyIsland" }"#)
            .unwrap();
        find_project(&base.join("Content")).expect("project should be discoverable")
    }

    #[test]
    fn find_project_walks_upward_and_reads_metadata() {
        let project = temp_project("find");
        assert!(project.project_file.to_string_lossy().ends_with("MyIsland.uefnproject"));
        assert_eq!(read_verse_path(&project).unwrap(), "/invaliddomain/MyIsland");
        assert_eq!(read_compat_version(&project).as_deref(), Some("41.20"));
        let _ = fs::remove_dir_all(&project.project_root);
    }

    #[test]
    fn find_project_returns_none_outside_projects() {
        let base = std::env::temp_dir();
        // temp dir itself must not look like a UEFN project
        assert!(find_file_with_extension(&base, "uefnproject").is_none());
    }

    #[test]
    fn is_forest_marker_requires_the_exact_header() {
        let base = std::env::temp_dir().join(format!("forest-marker-{}", std::process::id()));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(&base).unwrap();
        let marker = base.join("TestScope.verse");
        fs::write(&marker, marker_content("TestScope", &MarkerAccess::Public)).unwrap();
        assert!(is_forest_marker(&marker));
        let user_file = base.join("User.verse");
        fs::write(&user_file, "# my comment\nAdd<public>(A:int, B:int):int = A + B\n").unwrap();
        assert!(!is_forest_marker(&user_file));
        let _ = fs::remove_dir_all(&base);
    }

    #[test]
    fn workspace_roots_merge_project_and_authored_manifests() {
        let base = std::env::temp_dir().join(format!("forest-ws-roots-{}", std::process::id()));
        let _ = fs::remove_dir_all(&base);
        let content = base.join("Content");
        let mount = content.join("ForestPackages");
        fs::create_dir_all(&mount).unwrap();
        fs::write(base.join("Island.uefnproject"), "{}").unwrap();
        fs::write(base.join("Island.uplugin"), r#"{ "VersePath": "/x/Island" }"#).unwrap();

        // Project manifest declares one dep.
        fs::write(
            content.join("forest.json"),
            r#"{ "platform": "uefn", "dependencies": { "acme/shared": "^1.0.0" } }"#,
        )
        .unwrap();
        // Authored package A declares its own dep + the shared one with a
        // DIFFERENT requirement (both must hold: comma-joined = semver AND).
        let pkg_a = mount.join("mine").join("PkgA");
        fs::create_dir_all(&pkg_a).unwrap();
        fs::write(
            pkg_a.join("forest.json"),
            r#"{ "platform": "uefn", "name": "PkgA", "dependencies": { "acme/shared": "^1.2.0", "other/util": "^3.0.0" } }"#,
        )
        .unwrap();
        // Authored package B declares the shared dep with the SAME req (no join).
        let pkg_b = mount.join("mine").join("PkgB");
        fs::create_dir_all(&pkg_b).unwrap();
        fs::write(
            pkg_b.join("forest.json"),
            r#"{ "platform": "uefn", "name": "PkgB", "dependencies": { "acme/shared": "^1.0.0" } }"#,
        )
        .unwrap();
        // An INSTALLED (receipt-carrying) package's manifest must NOT count.
        let installed = mount.join("vendor").join("Dep");
        fs::create_dir_all(&installed).unwrap();
        fs::write(installed.join("forest.json"), r#"{ "dependencies": { "sneaky/extra": "^9.0.0" } }"#).unwrap();
        fs::write(
            installed.join(crate::receipts::RECEIPT_FILE),
            r#"{ "name": "vendor/dep", "version": "1.0.0", "integrity": "aa", "root": "" }"#,
        )
        .unwrap();

        let project = find_project(&content).unwrap();
        let roots = gather_workspace_roots(&project).unwrap();

        assert_eq!(roots.len(), 2, "shared dep dedupes; installed manifests ignored: {:?}", roots.keys().collect::<Vec<_>>());
        let shared = &roots["acme/shared"];
        assert_eq!(shared.version, "^1.0.0, ^1.2.0", "differing reqs are ANDed, identical req not re-joined");
        assert_eq!(roots["other/util"].version, "^3.0.0");
        assert!(!roots.contains_key("sneaky/extra"));

        let _ = fs::remove_dir_all(&base);
    }

    #[test]
    fn editor_probe_missing_mount_is_not_running() {
        let missing = std::env::temp_dir().join("forest-no-such-mount-xyz");
        assert!(!is_editor_running(&missing).unwrap());
    }

    #[test]
    fn lint_flags_root_function_defs_only() {
        assert_eq!(detect_function_def("Add(X:int, Y:int):int = X + Y"), Some("Add"));
        assert_eq!(detect_function_def("Add<public>(X:int, Y:int):int = X + Y"), Some("Add"));
        assert_eq!(detect_function_def("Fn<public><decides>(X:int):int = X"), Some("Fn"));
        assert_eq!(detect_function_def("using { ForestPackages.a.b }"), None);
        assert_eq!(detect_function_def("my_device := class(creative_device):"), None);
        assert_eq!(detect_function_def("    OnBegin<override>()<suspends>:void="), None);
        assert_eq!(detect_function_def("# Add(X:int) comment"), None);
        assert_eq!(detect_function_def(""), None);
    }
}
